Update render-readme.yaml

diff --git a/.github/workflows/render-readme.yaml b/.github/workflows/render-readme.yaml
--- a/.github/workflows/render-readme.yaml
+++ b/.github/workflows/render-readme.yaml
@@ -1,34 +1,70 @@
+# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
+# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
 on:
   push:
-    branches: main
+    paths: ['**.Rmd']
 
-name: Render README
+name: render-rmarkdown
 
 jobs:
-  render:
-    name: Render README
-    runs-on: macOS-latest
+  render-rmarkdown:
+    runs-on: ubuntu-latest
+    env:
+      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
     steps:
-      - uses: actions/checkout@v2
-      - uses: r-lib/actions/setup-r@v1
-      - uses: r-lib/actions/setup-pandoc@v1
-      - name: Install rmarkdown, remotes, and the local package
+      - name: Checkout repo
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+
+      - uses: r-lib/actions/setup-pandoc@v2
+
+      - uses: r-lib/actions/setup-r@v2
+
+      - uses: r-lib/actions/setup-renv@v2
+      
+      - name: Render Rmarkdown files and Commit Results
         run: |
-          install.packages("remotes")
-          remotes::install_local(".")
-          remotes::install_cran("rmarkdown")
-          remotes::install_cran("ggplot2")
-          remotes::install_cran("scales")
-          remotes::install_cran("glue")
-          remotes::install_cran("dplyr")
-          remotes::install_cran("gapminder")
-        shell: Rscript {0}
-      - name: Render README
-        run: Rscript -e 'rmarkdown::render("README.Rmd")'
-      - name: Commit results
-        run: |
-          git add README.md man/figures/README-*
-          git config --local user.email "actions@github.com"
-          git config --local user.name "GitHub Actions"
-          git commit README.md -m 'Re-build README.Rmd' || echo "No changes to commit"
+          RMD_PATH=($(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '[.]Rmd$'))
+          Rscript -e 'for (f in commandArgs(TRUE)) if (file.exists(f)) rmarkdown::render(f)' ${RMD_PATH[*]}
+          git config --local user.name "$GITHUB_ACTOR"
+          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
+          git commit ${RMD_PATH[*]/.Rmd/.md} -m 'Re-build Rmarkdown files' || echo "No changes to commit"
           git push origin || echo "No changes to commit"
+
+
+#on:
+  #push:
+    #branches: main
+
+#name: Render README
+
+#jobs:
+  #render:
+    #name: Render README
+    #runs-on: macOS-latest
+    #steps:
+      #- uses: actions/checkout@v2
+      #- uses: r-lib/actions/setup-r@v1
+      #- uses: r-lib/actions/setup-pandoc@v1
+     # - name: Install rmarkdown, remotes, and the local package
+        #run: |
+          #install.packages("remotes")
+          #remotes::install_local(".")
+          #remotes::install_cran("rmarkdown")
+          #remotes::install_cran("ggplot2")
+          #remotes::install_cran("scales")
+          #remotes::install_cran("glue")
+          #remotes::install_cran("dplyr")
+          #remotes::install_cran("gapminder")
+        #shell: Rscript {0}
+      #- name: Render README
+        #run: Rscript -e 'rmarkdown::render("README.Rmd")'
+      #- name: Commit results
+        #run: |
+          #git add README.md man/figures/README-*
+          #git config --local user.email "actions@github.com"
+          #git config --local user.name "GitHub Actions"
+          #git commit README.md -m 'Re-build README.Rmd' || echo "No changes to commit"
+          #git push origin || echo "No changes to commit"
+          
